<?php
/**
 * Created by PhpStorm.
 * User: O
 * Date: 10/3/2016
 * Time: 12:57 PM
 */
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$x=0;
$y=1;
$z=0;
$j=0;
$k=0;
for(;$y<4000000;){
    $z=$x+$y;
  //  echo "<br>Digit ".$z." <br>";
    $x=$y;
    $y=$z;

    // i don't understand that is  "find the sum of the even-valued terms." means
    // and at this point we have this code

    if ($x % 2 == 0){
        echo "<br>Digit ".$k." <br>";
        echo "+";
        $k=$k+$x;
    }
    else{
        $j=$k+$x;
    }
}

//echo "<br>Число ".$z." <br>";
//echo "<br>Число ".$j." <br>";
echo "<br>Digit ".$k." <br>";